name: Tests Pull Request
on:
  - pull_request

jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - run: go version
      - name: golangci-lint
        uses: golangci/golangci-lint-action@fix-75
      - run: go version
